version: '3.8'
services:
  pyqt-app:
    build: .
    image: pyqt-signature-app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    network_mode: host